[book]
authors = ["Kohei Watanabe"]
language = "ja"
title = "Web開発をはじめよう"

[output.html]
edit-url-template = "https://github.com/kou029w/intro-to-web-dev/edit/main/{path}"
git-repository-url = "https://github.com/kou029w/intro-to-web-dev"
site-url = "/intro-to-web-dev/"
additional-js = [
  "js/external-links.js",
  "js/regexp-search.js",
]
